/* Generated By:JavaCC: Do not edit this line. TraduccionConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TraduccionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN_PARENTHESIS = 1;
  /** RegularExpression Id. */
  int CLOSE_PARENTHESIS = 2;
  /** RegularExpression Id. */
  int SUMA = 3;
  /** RegularExpression Id. */
  int MULT = 4;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int IDE = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"*\"",
    "<NUMBER>",
    "<IDE>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
  };

}
